
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage-material
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  banner:
    location: classpath:banner.txt
  security:
    user:
      name: admin
      password: admin
      roles: USER